# Generated by Django 3.1.5 on 2021-02-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account', models.CharField(max_length=20, unique=True)),
                ('Password', models.CharField(max_length=30)),
                ('Type', models.CharField(choices=[('Student', '学生'), ('Teacher', '导师')], default='学生', max_length=30)),
            ],
        ),
    ]
